[package]
name = "ndarray-conv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = {version = "0.15", features = ["rayon"]}
num = "0.4"
rustfft = "6.1"
ndrustfft = "0.3"
realfft = "3.2"
transpose = "0.2"

# [dev-dependencies]
ndarray-rand = "*"
